# application-dev.yml

config:
  domain: "http://localhost:8080/"
  admin-id: "admin"
  admin-pw: "admin"
  jwt-secret-key: "a_hoowave_and_secure_256_bit_secret_key_for_jwt"

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/d_toolbox?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 0318

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        bytecode:
          format_sql: true

springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    url: /api/docs
    path: /api/docs-ui