# application-dev.yml

config:
  domain: "http://localhost:8080/"

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/d_toolbox?allowPublicKeyRetrieval=true&useSSL=false
    username: hoowave
    password:

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        bytecode:
          format_sql: true