# application-dev.yml

config:
  domain: "http://localhost:8080/"
  jwt-secret-key: "a_hoowave_and_secure_256_bit_secret_key_for_jwt"

# System 환경변수 처리
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        bytecode:
          format_sql: true