# application-dev.yml

config:
  domain: "https://api-dev.hoowave.org/"
  jwt-secret-key: ${JWT_SECRET_KEY}

# System 환경변수 처리
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        bytecode:
          format_sql: true