# ToolBox Configuration
config:
  domain: http://localhost:8080/

# Spring Datasource Configuration
spring:
  application:
    name: toolbox
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/d_toolbox
    username: hoowave
    password:

  # JPA and Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        bytecode:
          format_sql: true